-- Backfill country_code (ISO 3166-1 alpha-2) for all teams
-- Used by flag-icons library: "fi fi-{country_code}"

UPDATE teams SET country_code = 'dz' WHERE short_code = 'ALG';
UPDATE teams SET country_code = 'ar' WHERE short_code = 'ARG';
UPDATE teams SET country_code = 'au' WHERE short_code = 'AUS';
UPDATE teams SET country_code = 'at' WHERE name = 'Austria';
UPDATE teams SET country_code = 'be' WHERE short_code = 'BEL';
UPDATE teams SET country_code = 'ba' WHERE short_code = 'BOS';
UPDATE teams SET country_code = 'br' WHERE short_code = 'BRA';
UPDATE teams SET country_code = 'ca' WHERE short_code = 'CAN';
UPDATE teams SET country_code = 'cv' WHERE short_code = 'CAP';
UPDATE teams SET country_code = 'co' WHERE short_code = 'COL';
UPDATE teams SET country_code = 'cd' WHERE short_code = 'CON';
UPDATE teams SET country_code = 'hr' WHERE short_code = 'CRO';
UPDATE teams SET country_code = 'cw' WHERE short_code = 'CUR';
UPDATE teams SET country_code = 'cz' WHERE short_code = 'CZE';
UPDATE teams SET country_code = 'ec' WHERE short_code = 'ECU';
UPDATE teams SET country_code = 'eg' WHERE short_code = 'EGY';
UPDATE teams SET country_code = 'gb-eng' WHERE short_code = 'ENG';
UPDATE teams SET country_code = 'fr' WHERE short_code = 'FRA';
UPDATE teams SET country_code = 'de' WHERE short_code = 'GER';
UPDATE teams SET country_code = 'gh' WHERE short_code = 'GHA';
UPDATE teams SET country_code = 'ht' WHERE short_code = 'HAI';
UPDATE teams SET country_code = 'ir' WHERE short_code = 'IRA';
UPDATE teams SET country_code = 'iq' WHERE name = 'Iraq';
UPDATE teams SET country_code = 'ci' WHERE short_code = 'IVO';
UPDATE teams SET country_code = 'jp' WHERE short_code = 'JAP';
UPDATE teams SET country_code = 'jo' WHERE short_code = 'JOR';
UPDATE teams SET country_code = 'mx' WHERE short_code = 'MEX';
UPDATE teams SET country_code = 'ma' WHERE short_code = 'MOR';
UPDATE teams SET country_code = 'nl' WHERE short_code = 'NET';
UPDATE teams SET country_code = 'nz' WHERE short_code = 'ZEA';
UPDATE teams SET country_code = 'no' WHERE short_code = 'NOR';
UPDATE teams SET country_code = 'pa' WHERE short_code = 'PAN';
UPDATE teams SET country_code = 'py' WHERE short_code = 'PAR';
UPDATE teams SET country_code = 'pt' WHERE short_code = 'POR';
UPDATE teams SET country_code = 'qa' WHERE short_code = 'QAT';
UPDATE teams SET country_code = 'sa' WHERE short_code = 'SAU';
UPDATE teams SET country_code = 'gb-sct' WHERE short_code = 'SCO';
UPDATE teams SET country_code = 'sn' WHERE short_code = 'SEN';
UPDATE teams SET country_code = 'za' WHERE name = 'South Africa';
UPDATE teams SET country_code = 'kr' WHERE name = 'South Korea';
UPDATE teams SET country_code = 'es' WHERE short_code = 'SPA';
UPDATE teams SET country_code = 'se' WHERE short_code = 'SWE';
UPDATE teams SET country_code = 'ch' WHERE short_code = 'SWI';
UPDATE teams SET country_code = 'tn' WHERE short_code = 'TUN';
UPDATE teams SET country_code = 'tr' WHERE short_code = 'TUR';
UPDATE teams SET country_code = 'uy' WHERE short_code = 'URU';
UPDATE teams SET country_code = 'us' WHERE short_code = 'USA';
UPDATE teams SET country_code = 'uz' WHERE short_code = 'UZB';
