ALTER TABLE "teams" ADD COLUMN "transfermarkt_id" integer;
ALTER TABLE "teams" ADD COLUMN "squad_market_value" integer;
ALTER TABLE "sync_state" ADD COLUMN "transfermarkt_sync_enabled" boolean DEFAULT false NOT NULL;
ALTER TABLE "sync_state" ADD COLUMN "last_transfermarkt_sync_at" timestamp with time zone;

-- Seed transfermarkt_id for WC2026 national teams (by short_code)
UPDATE "teams" SET "transfermarkt_id" = 3505 WHERE "short_code" = 'USA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 6303 WHERE "short_code" = 'MEX' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3510 WHERE "short_code" = 'CAN' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3577 WHERE "short_code" = 'PAN' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3437 WHERE "short_code" = 'ARG' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3700 WHERE "short_code" = 'CHI' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3584 WHERE "short_code" = 'PER' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3433 WHERE "short_code" = 'AUS' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 5750 WHERE "short_code" = 'ECU' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3504 WHERE "short_code" = 'VEN' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 9171 WHERE "short_code" = 'NZL' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3439 WHERE "short_code" = 'BRA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3816 WHERE "short_code" = 'COL' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3581 WHERE "short_code" = 'PAR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3434 WHERE "short_code" = 'CMR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3468 WHERE "short_code" = 'ESP' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3375 WHERE "short_code" = 'POR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3575 WHERE "short_code" = 'MAR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3377 WHERE "short_code" = 'FRA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3379 WHERE "short_code" = 'NED' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3499 WHERE "short_code" = 'SEN' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3589 WHERE "short_code" = 'KOR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3300 WHERE "short_code" = 'ENG' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3556 WHERE "short_code" = 'CRO' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3444 WHERE "short_code" = 'NGA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3438 WHERE "short_code" = 'SRB' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3262 WHERE "short_code" = 'GER' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3435 WHERE "short_code" = 'JPN' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3807 WHERE "short_code" = 'KSA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3670 WHERE "short_code" = 'TUN' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3382 WHERE "short_code" = 'BEL' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3699 WHERE "short_code" = 'UKR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3674 WHERE "short_code" = 'MLI' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 8497 WHERE "short_code" = 'CRC' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3376 WHERE "short_code" = 'ITA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3384 WHERE "short_code" = 'SUI' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3591 WHERE "short_code" = 'CIV' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3590 WHERE "short_code" = 'HON' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3442 WHERE "short_code" = 'POL' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3441 WHERE "short_code" = 'GHA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3449 WHERE "short_code" = 'URU' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3436 WHERE "short_code" = 'DEN' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3383 WHERE "short_code" = 'AUT' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3672 WHERE "short_code" = 'EGY' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 14162 WHERE "short_code" = 'QAT' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3380 WHERE "short_code" = 'SCO' AND "team_type" = 'national';

-- API-football sync duplicates (different short_codes)
UPDATE "teams" SET "transfermarkt_id" = 3614 WHERE "short_code" = 'ALG' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3806 WHERE "short_code" = 'SOU1' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 15737 WHERE "short_code" = 'JOR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3560 WHERE "short_code" = 'IRA7' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3563 WHERE "short_code" = 'UZB' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3699 WHERE "short_code" = 'UKR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 8497 WHERE "short_code" = 'CRC' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3582 WHERE "short_code" = 'IRA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 14161 WHERE "short_code" = 'HAI' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3557 WHERE "short_code" = 'SWE' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3440 WHERE "short_code" = 'NOR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3445 WHERE "short_code" = 'CZE' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3381 WHERE "short_code" = 'TUR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3446 WHERE "short_code" = 'BOS' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3854 WHERE "short_code" = 'CON' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 4311 WHERE "short_code" = 'CAP' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 32364 WHERE "short_code" = 'CUR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3468 WHERE "short_code" = 'SPA' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3435 WHERE "short_code" = 'JAP' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3384 WHERE "short_code" = 'SWI' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3589 WHERE "short_code" = 'SOU' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3807 WHERE "short_code" = 'SAU' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3575 WHERE "short_code" = 'MOR' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3383 WHERE "short_code" = 'AUS5' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3379 WHERE "short_code" = 'NET' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 3591 WHERE "short_code" = 'IVO' AND "team_type" = 'national';
UPDATE "teams" SET "transfermarkt_id" = 9171 WHERE "short_code" = 'ZEA' AND "team_type" = 'national';
